name: k8s image sync
on: push
jobs:
  k8s-image-sync:
    name: k8s image sync
    runs-on: ubuntu-latest
    steps:
    - name: sync
      uses: samlaudev/actions/k8s-image-sync@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        owner: ${{ secrets.DOCKER_USERNAME }}
        kubernetes_version: v1.14.8 
